### ISSUE TITLE
Parsing error when escaped inside a string

### ISSUE THREAD

**Issue by elamhut** [ValvePython/vdf#37] opened 2021-05-11 22:57 UTC
Trying to use this for my build tool, I'm getting some errors when the parser tries to deal with Paths such as when parsing:

"appbuild"
{
	"appid" "111111111"
	"desc" "Description you want"
	"buildoutput" "D:\SteamSDK\tools\ContentBuilder\output"
	"contentroot" ""
	"setlive" "internaltest"
	"preview" "0"
	"local"	""
	"depots"
	{
		"111111111"	"D:\SteamSDK\tools\ContentBuilder\scripts\generic_depot.vdf"
	}
}

This is what it's returning

"appbuild"
{
	"appid" "111111111"
	"desc" "Description you want"
	`"buildoutput" "D:\\SteamSDK\tools\\ContentBuilder\\output"`
	"contentroot" ""
	"setlive" "internaltest"
	"preview" "0"
	"local" ""
	"depots"
	{
		"111111111" `"D:\\SteamSDK\tools\\ContentBuilder\\scripts\\generic_depot.vdf"`
	}
}

Notice D:\\SteamSDK\tools\\ContentBuilder\\scripts\\generic_depot.vdf

Where \tools it's only giving one backslash because \t is an escape command.

**Comment by rossengeorgiev** [comment] 2021-05-12 17:38
Duplicate of #28

**Closed** 2021-05-12 17:39 UTC
Labels: bug, duplicate
